### PR TITLE
Add copy fallback for lu(A')

### PR DESCRIPTION
**Pull request by rayegun**
I don't think this it's really ideal to do a copy, but the copy shouldn't be a big issue in most cases. Solves JuliaSparse/SparseArrays.jl#131

### CODE REVIEW

**Comment by rayegun** [comment]
Actually @ViralBShah can we not just have `lu(A') = lu(A)'`? That way we don't do any materializing, and we hit the `lu(A)' \ b` specialization. Is there a gotcha I'm missing there?

**Comment by ViralBShah** [comment]
What happens in the dense case?

**Comment by rayegun** [comment]
Dense does a copy, and after talking with Tim I'll keep `lu(A') = lu(copy(A))` so that the user can decide what they want (different computation patterns etc). It'll have different properties. I'll add some tests here shortly.

**Comment by ViralBShah** [comment]
It should be `lu(copy(A'))` right?

**Comment by rayegun** [comment]
I was kind of using `'` as a type tag there, but yes.

**Comment by ViralBShah** [comment]
It would be good to add a test too, and merge.

**Pull request merged**
