### PR TITLE
Upgrade Clang.jl version, regenerate bindings for Julia 1.7, add docs

### PR DESCRIPTION
**Pull request by Gnimuc**
1. `printer_blacklist`->`output_ignorelist`
2. `functionlike_macro_whitelist`->`functionlike_macro_includelist`
3. add missing compilation flag `-D'SuiteSparse_long_max=9223372036854775801'`

### CODE REVIEW

**Comment by ViralBShah** [comment]
@Gnimuc Do we need to get this in?

**Comment by Gnimuc** [comment]
It looks like @Wimmerer has been working on a new KLU project: https://github.com/JuliaSparse/KLU.jl. Should we remove the header klu.h here?

**Comment by rayegun** [comment]
There shouldn't be any need for it here. I need to merge the Clang.jl PR in that project also.

**Comment by ViralBShah** [comment]
Yes, I am glad we kept KLU separate from here as its own package. The header can be removed.

**Comment by Gnimuc** [comment]
I regenerated those bindings without `klu.h` within Julia 1.7.1. Should I rerun the generator with Julia's latest master?

**Comment by ViralBShah** [comment]
Shouldn't we rerun it with Julia 1.7?

**Comment by Gnimuc** [comment]
If the version(API) of SuiteSparse_jll has not been changed between Julia 1.7 and the 1.8-dev, then I think this should be fine.  At least those tests are passed on nightly.

**Comment by ViralBShah** [comment]
Ok

**Comment by ViralBShah** [comment]
Right, and we merge newer versions here into Julia nightlies... I wonder if we should also test the latest stable version.

**Comment by Gnimuc** [comment]
I don't know much about the regular stdlib development routine. If we do need to apply this change to a stable version, we can merge this into the DEV branch first and then do regular backports, that's where we run those tests for the stable version.

**Comment by ViralBShah** [comment]
Rebased to master where I just merged LTS into the CI. Ideally, if we can keep LTS always working, that's great. At the very least this will tell us if the PR breaks LTS, in which case we'll have to put in some version checks.

**Comment by ViralBShah** [comment]
The only thing we should do is [document in the README how to generate the Clang.jl wrappers](https://github.com/JuliaLang/SuiteSparse.jl/issues/41).

**Review by ViralBShah — APPROVED** [review]

**Pull request merged**
